<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDIP2gN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDIP2gN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDIP2gN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDIP2gN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXDIP2gN\App_KernelDevDebugContainer([
    'container.build_hash' => 'XDIP2gN',
    'container.build_id' => 'c22ed617',
    'container.build_time' => 1776704251,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDIP2gN');
