# .github/workflows/ping-url.yml

name: Update repo

on:
  push:
    branches:
      - main

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Visit URL
        run: |
          curl --fail https://aloxoblack.com/updateRepo
